load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "jetstream_libc",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = "2021",
    deps = all_crate_deps(normal = True),
)
