# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_websocket"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_ufs"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_rpc"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_9p"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_libc"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_quic"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_wireformat"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_macros"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/components/jetstream_iroh"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/fuzz"
    schedule:
      interval: "daily"
